name: test
on: push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: checkout
        uses: actions/checkout@v3
      - name: test and measure coverage
        run: make test_cov_out
      - name: upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
      - name: scan
        run: make scan
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup env
        run: |
          cd scripts/e2e
          docker-compose up -d
      - name: install cli
        run: |
          curl https://raw.githubusercontent.com/findy-network/findy-agent-cli/HEAD/install.sh > install.sh
          chmod a+x install.sh
          sudo ./install.sh -b /bin
      - name: test
        run: ./scripts/test.sh
